# Generated by Django 4.2.7 on 2024-02-20 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0009_alter_rubric_options_rubric_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevRubric',
            fields=[
            ],
            options={
                'ordering': ['-name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bboard.rubric',),
        ),
    ]
