# Generated by Django 4.2.7 on 2024-03-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_revrubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='bb/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
