# Generated by Django 4.2.7 on 2024-02-29 14:02

from django.db import migrations, models
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_pgsproject_pgsproject2_pgsproject3_pgsrubric_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=testapp.models.get_timestamp_path, verbose_name='Изображение')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.DeleteModel(
            name='PGSProject',
        ),
        migrations.DeleteModel(
            name='PGSProject2',
        ),
        migrations.DeleteModel(
            name='PGSProject3',
        ),
    ]
