# Generated by Django 4.2.7 on 2024-02-13 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_message_privatemessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AditMachine',
            fields=[
                ('machine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testapp.machine')),
                ('car_model', models.CharField(max_length=30)),
                ('car_year', models.PositiveIntegerField()),
                ('car_make', models.CharField(max_length=30)),
            ],
            bases=('testapp.machine',),
        ),
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['name']},
        ),
    ]
