# Generated by Django 4.2.7 on 2024-03-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
