# Generated by Django 4.2.7 on 2024-02-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_aditmachine_alter_machine_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={},
        ),
        migrations.DeleteModel(
            name='AditMachine',
        ),
    ]
