# Generated by Django 4.2.7 on 2024-02-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grandchildren',
            fields=[
            ],
            options={
                'ordering': ['age'],
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('testapp.children',),
        ),
    ]
